/**
 * 国家/地区电话区号表（注册手机号国际化）。
 * 常用亚太地区置顶，其余按英文名排序；en/zh/dial/iso 均可被 filterCountries 搜索命中。
 */
export const COUNTRY_CODES = [
  { iso: 'JP', zh: '日本', en: 'Japan', dial: '+81' },
  { iso: 'CN', zh: '中国大陆', en: 'China', dial: '+86' },
  { iso: 'HK', zh: '中国香港', en: 'Hong Kong', dial: '+852' },
  { iso: 'MO', zh: '中国澳门', en: 'Macao', dial: '+853' },
  { iso: 'TW', zh: '中国台湾', en: 'Taiwan', dial: '+886' },
  { iso: 'KR', zh: '韩国', en: 'South Korea', dial: '+82' },
  { iso: 'SG', zh: '新加坡', en: 'Singapore', dial: '+65' },
  { iso: 'US', zh: '美国', en: 'United States', dial: '+1' },
  { iso: 'AF', zh: '阿富汗', en: 'Afghanistan', dial: '+93' },
  { iso: 'AL', zh: '阿尔巴尼亚', en: 'Albania', dial: '+355' },
  { iso: 'DZ', zh: '阿尔及利亚', en: 'Algeria', dial: '+213' },
  { iso: 'AD', zh: '安道尔', en: 'Andorra', dial: '+376' },
  { iso: 'AO', zh: '安哥拉', en: 'Angola', dial: '+244' },
  { iso: 'AR', zh: '阿根廷', en: 'Argentina', dial: '+54' },
  { iso: 'AM', zh: '亚美尼亚', en: 'Armenia', dial: '+374' },
  { iso: 'AU', zh: '澳大利亚', en: 'Australia', dial: '+61' },
  { iso: 'AT', zh: '奥地利', en: 'Austria', dial: '+43' },
  { iso: 'AZ', zh: '阿塞拜疆', en: 'Azerbaijan', dial: '+994' },
  { iso: 'BS', zh: '巴哈马', en: 'Bahamas', dial: '+1242' },
  { iso: 'BH', zh: '巴林', en: 'Bahrain', dial: '+973' },
  { iso: 'BD', zh: '孟加拉国', en: 'Bangladesh', dial: '+880' },
  { iso: 'BB', zh: '巴巴多斯', en: 'Barbados', dial: '+1246' },
  { iso: 'BY', zh: '白俄罗斯', en: 'Belarus', dial: '+375' },
  { iso: 'BE', zh: '比利时', en: 'Belgium', dial: '+32' },
  { iso: 'BZ', zh: '伯利兹', en: 'Belize', dial: '+501' },
  { iso: 'BJ', zh: '贝宁', en: 'Benin', dial: '+229' },
  { iso: 'BT', zh: '不丹', en: 'Bhutan', dial: '+975' },
  { iso: 'BO', zh: '玻利维亚', en: 'Bolivia', dial: '+591' },
  { iso: 'BA', zh: '波黑', en: 'Bosnia and Herzegovina', dial: '+387' },
  { iso: 'BW', zh: '博茨瓦纳', en: 'Botswana', dial: '+267' },
  { iso: 'BR', zh: '巴西', en: 'Brazil', dial: '+55' },
  { iso: 'BN', zh: '文莱', en: 'Brunei', dial: '+673' },
  { iso: 'BG', zh: '保加利亚', en: 'Bulgaria', dial: '+359' },
  { iso: 'BF', zh: '布基纳法索', en: 'Burkina Faso', dial: '+226' },
  { iso: 'BI', zh: '布隆迪', en: 'Burundi', dial: '+257' },
  { iso: 'KH', zh: '柬埔寨', en: 'Cambodia', dial: '+855' },
  { iso: 'CM', zh: '喀麦隆', en: 'Cameroon', dial: '+237' },
  { iso: 'CA', zh: '加拿大', en: 'Canada', dial: '+1' },
  { iso: 'CV', zh: '佛得角', en: 'Cape Verde', dial: '+238' },
  { iso: 'CF', zh: '中非共和国', en: 'Central African Republic', dial: '+236' },
  { iso: 'TD', zh: '乍得', en: 'Chad', dial: '+235' },
  { iso: 'CL', zh: '智利', en: 'Chile', dial: '+56' },
  { iso: 'CO', zh: '哥伦比亚', en: 'Colombia', dial: '+57' },
  { iso: 'KM', zh: '科摩罗', en: 'Comoros', dial: '+269' },
  { iso: 'CG', zh: '刚果(布)', en: 'Congo', dial: '+242' },
  { iso: 'CD', zh: '刚果(金)', en: 'DR Congo', dial: '+243' },
  { iso: 'CR', zh: '哥斯达黎加', en: 'Costa Rica', dial: '+506' },
  { iso: 'CI', zh: '科特迪瓦', en: "Cote d'Ivoire", dial: '+225' },
  { iso: 'HR', zh: '克罗地亚', en: 'Croatia', dial: '+385' },
  { iso: 'CU', zh: '古巴', en: 'Cuba', dial: '+53' },
  { iso: 'CY', zh: '塞浦路斯', en: 'Cyprus', dial: '+357' },
  { iso: 'CZ', zh: '捷克', en: 'Czechia', dial: '+420' },
  { iso: 'DK', zh: '丹麦', en: 'Denmark', dial: '+45' },
  { iso: 'DJ', zh: '吉布提', en: 'Djibouti', dial: '+253' },
  { iso: 'DO', zh: '多米尼加', en: 'Dominican Republic', dial: '+1809' },
  { iso: 'EC', zh: '厄瓜多尔', en: 'Ecuador', dial: '+593' },
  { iso: 'EG', zh: '埃及', en: 'Egypt', dial: '+20' },
  { iso: 'SV', zh: '萨尔瓦多', en: 'El Salvador', dial: '+503' },
  { iso: 'GQ', zh: '赤道几内亚', en: 'Equatorial Guinea', dial: '+240' },
  { iso: 'ER', zh: '厄立特里亚', en: 'Eritrea', dial: '+291' },
  { iso: 'EE', zh: '爱沙尼亚', en: 'Estonia', dial: '+372' },
  { iso: 'SZ', zh: '斯威士兰', en: 'Eswatini', dial: '+268' },
  { iso: 'ET', zh: '埃塞俄比亚', en: 'Ethiopia', dial: '+251' },
  { iso: 'FJ', zh: '斐济', en: 'Fiji', dial: '+679' },
  { iso: 'FI', zh: '芬兰', en: 'Finland', dial: '+358' },
  { iso: 'FR', zh: '法国', en: 'France', dial: '+33' },
  { iso: 'GA', zh: '加蓬', en: 'Gabon', dial: '+241' },
  { iso: 'GM', zh: '冈比亚', en: 'Gambia', dial: '+220' },
  { iso: 'GE', zh: '格鲁吉亚', en: 'Georgia', dial: '+995' },
  { iso: 'DE', zh: '德国', en: 'Germany', dial: '+49' },
  { iso: 'GH', zh: '加纳', en: 'Ghana', dial: '+233' },
  { iso: 'GR', zh: '希腊', en: 'Greece', dial: '+30' },
  { iso: 'GL', zh: '格陵兰', en: 'Greenland', dial: '+299' },
  { iso: 'GT', zh: '危地马拉', en: 'Guatemala', dial: '+502' },
  { iso: 'GN', zh: '几内亚', en: 'Guinea', dial: '+224' },
  { iso: 'GW', zh: '几内亚比绍', en: 'Guinea-Bissau', dial: '+245' },
  { iso: 'GY', zh: '圭亚那', en: 'Guyana', dial: '+592' },
  { iso: 'HT', zh: '海地', en: 'Haiti', dial: '+509' },
  { iso: 'HN', zh: '洪都拉斯', en: 'Honduras', dial: '+504' },
  { iso: 'HU', zh: '匈牙利', en: 'Hungary', dial: '+36' },
  { iso: 'IS', zh: '冰岛', en: 'Iceland', dial: '+354' },
  { iso: 'IN', zh: '印度', en: 'India', dial: '+91' },
  { iso: 'ID', zh: '印度尼西亚', en: 'Indonesia', dial: '+62' },
  { iso: 'IR', zh: '伊朗', en: 'Iran', dial: '+98' },
  { iso: 'IQ', zh: '伊拉克', en: 'Iraq', dial: '+964' },
  { iso: 'IE', zh: '爱尔兰', en: 'Ireland', dial: '+353' },
  { iso: 'IL', zh: '以色列', en: 'Israel', dial: '+972' },
  { iso: 'IT', zh: '意大利', en: 'Italy', dial: '+39' },
  { iso: 'JM', zh: '牙买加', en: 'Jamaica', dial: '+1876' },
  { iso: 'JO', zh: '约旦', en: 'Jordan', dial: '+962' },
  { iso: 'KZ', zh: '哈萨克斯坦', en: 'Kazakhstan', dial: '+7' },
  { iso: 'KE', zh: '肯尼亚', en: 'Kenya', dial: '+254' },
  { iso: 'KI', zh: '基里巴斯', en: 'Kiribati', dial: '+686' },
  { iso: 'KW', zh: '科威特', en: 'Kuwait', dial: '+965' },
  { iso: 'KG', zh: '吉尔吉斯斯坦', en: 'Kyrgyzstan', dial: '+996' },
  { iso: 'LA', zh: '老挝', en: 'Laos', dial: '+856' },
  { iso: 'LV', zh: '拉脱维亚', en: 'Latvia', dial: '+371' },
  { iso: 'LB', zh: '黎巴嫩', en: 'Lebanon', dial: '+961' },
  { iso: 'LS', zh: '莱索托', en: 'Lesotho', dial: '+266' },
  { iso: 'LR', zh: '利比里亚', en: 'Liberia', dial: '+231' },
  { iso: 'LY', zh: '利比亚', en: 'Libya', dial: '+218' },
  { iso: 'LI', zh: '列支敦士登', en: 'Liechtenstein', dial: '+423' },
  { iso: 'LT', zh: '立陶宛', en: 'Lithuania', dial: '+370' },
  { iso: 'LU', zh: '卢森堡', en: 'Luxembourg', dial: '+352' },
  { iso: 'MG', zh: '马达加斯加', en: 'Madagascar', dial: '+261' },
  { iso: 'MW', zh: '马拉维', en: 'Malawi', dial: '+265' },
  { iso: 'MY', zh: '马来西亚', en: 'Malaysia', dial: '+60' },
  { iso: 'MV', zh: '马尔代夫', en: 'Maldives', dial: '+960' },
  { iso: 'ML', zh: '马里', en: 'Mali', dial: '+223' },
  { iso: 'MT', zh: '马耳他', en: 'Malta', dial: '+356' },
  { iso: 'MH', zh: '马绍尔群岛', en: 'Marshall Islands', dial: '+692' },
  { iso: 'MR', zh: '毛里塔尼亚', en: 'Mauritania', dial: '+222' },
  { iso: 'MU', zh: '毛里求斯', en: 'Mauritius', dial: '+230' },
  { iso: 'MX', zh: '墨西哥', en: 'Mexico', dial: '+52' },
  { iso: 'FM', zh: '密克罗尼西亚', en: 'Micronesia', dial: '+691' },
  { iso: 'MD', zh: '摩尔多瓦', en: 'Moldova', dial: '+373' },
  { iso: 'MC', zh: '摩纳哥', en: 'Monaco', dial: '+377' },
  { iso: 'MN', zh: '蒙古', en: 'Mongolia', dial: '+976' },
  { iso: 'ME', zh: '黑山', en: 'Montenegro', dial: '+382' },
  { iso: 'MA', zh: '摩洛哥', en: 'Morocco', dial: '+212' },
  { iso: 'MZ', zh: '莫桑比克', en: 'Mozambique', dial: '+258' },
  { iso: 'MM', zh: '缅甸', en: 'Myanmar', dial: '+95' },
  { iso: 'NA', zh: '纳米比亚', en: 'Namibia', dial: '+264' },
  { iso: 'NR', zh: '瑙鲁', en: 'Nauru', dial: '+674' },
  { iso: 'NP', zh: '尼泊尔', en: 'Nepal', dial: '+977' },
  { iso: 'NL', zh: '荷兰', en: 'Netherlands', dial: '+31' },
  { iso: 'NZ', zh: '新西兰', en: 'New Zealand', dial: '+64' },
  { iso: 'NI', zh: '尼加拉瓜', en: 'Nicaragua', dial: '+505' },
  { iso: 'NE', zh: '尼日尔', en: 'Niger', dial: '+227' },
  { iso: 'NG', zh: '尼日利亚', en: 'Nigeria', dial: '+234' },
  { iso: 'KP', zh: '朝鲜', en: 'North Korea', dial: '+850' },
  { iso: 'MK', zh: '北马其顿', en: 'North Macedonia', dial: '+389' },
  { iso: 'NO', zh: '挪威', en: 'Norway', dial: '+47' },
  { iso: 'OM', zh: '阿曼', en: 'Oman', dial: '+968' },
  { iso: 'PK', zh: '巴基斯坦', en: 'Pakistan', dial: '+92' },
  { iso: 'PW', zh: '帕劳', en: 'Palau', dial: '+680' },
  { iso: 'PS', zh: '巴勒斯坦', en: 'Palestine', dial: '+970' },
  { iso: 'PA', zh: '巴拿马', en: 'Panama', dial: '+507' },
  { iso: 'PG', zh: '巴布亚新几内亚', en: 'Papua New Guinea', dial: '+675' },
  { iso: 'PY', zh: '巴拉圭', en: 'Paraguay', dial: '+595' },
  { iso: 'PE', zh: '秘鲁', en: 'Peru', dial: '+51' },
  { iso: 'PH', zh: '菲律宾', en: 'Philippines', dial: '+63' },
  { iso: 'PL', zh: '波兰', en: 'Poland', dial: '+48' },
  { iso: 'PT', zh: '葡萄牙', en: 'Portugal', dial: '+351' },
  { iso: 'PR', zh: '波多黎各', en: 'Puerto Rico', dial: '+1787' },
  { iso: 'QA', zh: '卡塔尔', en: 'Qatar', dial: '+974' },
  { iso: 'RO', zh: '罗马尼亚', en: 'Romania', dial: '+40' },
  { iso: 'RU', zh: '俄罗斯', en: 'Russia', dial: '+7' },
  { iso: 'RW', zh: '卢旺达', en: 'Rwanda', dial: '+250' },
  { iso: 'WS', zh: '萨摩亚', en: 'Samoa', dial: '+685' },
  { iso: 'SM', zh: '圣马力诺', en: 'San Marino', dial: '+378' },
  { iso: 'ST', zh: '圣多美和普林西比', en: 'Sao Tome and Principe', dial: '+239' },
  { iso: 'SA', zh: '沙特阿拉伯', en: 'Saudi Arabia', dial: '+966' },
  { iso: 'SN', zh: '塞内加尔', en: 'Senegal', dial: '+221' },
  { iso: 'RS', zh: '塞尔维亚', en: 'Serbia', dial: '+381' },
  { iso: 'SC', zh: '塞舌尔', en: 'Seychelles', dial: '+248' },
  { iso: 'SL', zh: '塞拉利昂', en: 'Sierra Leone', dial: '+232' },
  { iso: 'SK', zh: '斯洛伐克', en: 'Slovakia', dial: '+421' },
  { iso: 'SI', zh: '斯洛文尼亚', en: 'Slovenia', dial: '+386' },
  { iso: 'SB', zh: '所罗门群岛', en: 'Solomon Islands', dial: '+677' },
  { iso: 'SO', zh: '索马里', en: 'Somalia', dial: '+252' },
  { iso: 'ZA', zh: '南非', en: 'South Africa', dial: '+27' },
  { iso: 'SS', zh: '南苏丹', en: 'South Sudan', dial: '+211' },
  { iso: 'ES', zh: '西班牙', en: 'Spain', dial: '+34' },
  { iso: 'LK', zh: '斯里兰卡', en: 'Sri Lanka', dial: '+94' },
  { iso: 'SD', zh: '苏丹', en: 'Sudan', dial: '+249' },
  { iso: 'SR', zh: '苏里南', en: 'Suriname', dial: '+597' },
  { iso: 'SE', zh: '瑞典', en: 'Sweden', dial: '+46' },
  { iso: 'CH', zh: '瑞士', en: 'Switzerland', dial: '+41' },
  { iso: 'SY', zh: '叙利亚', en: 'Syria', dial: '+963' },
  { iso: 'TJ', zh: '塔吉克斯坦', en: 'Tajikistan', dial: '+992' },
  { iso: 'TZ', zh: '坦桑尼亚', en: 'Tanzania', dial: '+255' },
  { iso: 'TH', zh: '泰国', en: 'Thailand', dial: '+66' },
  { iso: 'TL', zh: '东帝汶', en: 'Timor-Leste', dial: '+670' },
  { iso: 'TG', zh: '多哥', en: 'Togo', dial: '+228' },
  { iso: 'TO', zh: '汤加', en: 'Tonga', dial: '+676' },
  { iso: 'TT', zh: '特立尼达和多巴哥', en: 'Trinidad and Tobago', dial: '+1868' },
  { iso: 'TN', zh: '突尼斯', en: 'Tunisia', dial: '+216' },
  { iso: 'TR', zh: '土耳其', en: 'Turkey', dial: '+90' },
  { iso: 'TM', zh: '土库曼斯坦', en: 'Turkmenistan', dial: '+993' },
  { iso: 'TV', zh: '图瓦卢', en: 'Tuvalu', dial: '+688' },
  { iso: 'UG', zh: '乌干达', en: 'Uganda', dial: '+256' },
  { iso: 'UA', zh: '乌克兰', en: 'Ukraine', dial: '+380' },
  { iso: 'AE', zh: '阿联酋', en: 'United Arab Emirates', dial: '+971' },
  { iso: 'GB', zh: '英国', en: 'United Kingdom', dial: '+44' },
  { iso: 'UY', zh: '乌拉圭', en: 'Uruguay', dial: '+598' },
  { iso: 'UZ', zh: '乌兹别克斯坦', en: 'Uzbekistan', dial: '+998' },
  { iso: 'VU', zh: '瓦努阿图', en: 'Vanuatu', dial: '+678' },
  { iso: 'VA', zh: '梵蒂冈', en: 'Vatican City', dial: '+379' },
  { iso: 'VE', zh: '委内瑞拉', en: 'Venezuela', dial: '+58' },
  { iso: 'VN', zh: '越南', en: 'Vietnam', dial: '+84' },
  { iso: 'YE', zh: '也门', en: 'Yemen', dial: '+967' },
  { iso: 'ZM', zh: '赞比亚', en: 'Zambia', dial: '+260' },
  { iso: 'ZW', zh: '津巴布韦', en: 'Zimbabwe', dial: '+263' },
  { iso: 'GD', zh: '格林纳达', en: 'Grenada', dial: '+1473' },
  { iso: 'AG', zh: '安提瓜和巴布达', en: 'Antigua and Barbuda', dial: '+1268' },
  { iso: 'DM', zh: '多米尼克', en: 'Dominica', dial: '+1767' },
  { iso: 'KN', zh: '圣基茨和尼维斯', en: 'Saint Kitts and Nevis', dial: '+1869' },
  { iso: 'LC', zh: '圣卢西亚', en: 'Saint Lucia', dial: '+1758' },
  { iso: 'VC', zh: '圣文森特和格林纳丁斯', en: 'Saint Vincent and the Grenadines', dial: '+1784' },
  { iso: 'GU', zh: '关岛', en: 'Guam', dial: '+1671' },
  { iso: 'MP', zh: '北马里亚纳群岛', en: 'Northern Mariana Islands', dial: '+1670' },
  { iso: 'AS', zh: '美属萨摩亚', en: 'American Samoa', dial: '+1684' },
  { iso: 'VI', zh: '美属维尔京群岛', en: 'US Virgin Islands', dial: '+1340' },
  { iso: 'VG', zh: '英属维尔京群岛', en: 'British Virgin Islands', dial: '+1284' },
  { iso: 'KY', zh: '开曼群岛', en: 'Cayman Islands', dial: '+1345' },
  { iso: 'BM', zh: '百慕大', en: 'Bermuda', dial: '+1441' },
  { iso: 'TC', zh: '特克斯和凯科斯群岛', en: 'Turks and Caicos Islands', dial: '+1649' },
  { iso: 'AI', zh: '安圭拉', en: 'Anguilla', dial: '+1264' },
  { iso: 'MS', zh: '蒙特塞拉特', en: 'Montserrat', dial: '+1664' },
  { iso: 'SX', zh: '荷属圣马丁', en: 'Sint Maarten', dial: '+1721' },
  { iso: 'CW', zh: '库拉索', en: 'Curacao', dial: '+599' },
  { iso: 'AW', zh: '阿鲁巴', en: 'Aruba', dial: '+297' },
  { iso: 'GF', zh: '法属圭亚那', en: 'French Guiana', dial: '+594' },
  { iso: 'GP', zh: '瓜德罗普', en: 'Guadeloupe', dial: '+590' },
  { iso: 'MQ', zh: '马提尼克', en: 'Martinique', dial: '+596' },
  { iso: 'RE', zh: '留尼汪', en: 'Reunion', dial: '+262' },
  { iso: 'PF', zh: '法属波利尼西亚', en: 'French Polynesia', dial: '+689' },
  { iso: 'NC', zh: '新喀里多尼亚', en: 'New Caledonia', dial: '+687' },
  { iso: 'FO', zh: '法罗群岛', en: 'Faroe Islands', dial: '+298' },
  { iso: 'GI', zh: '直布罗陀', en: 'Gibraltar', dial: '+350' },
  { iso: 'CK', zh: '库克群岛', en: 'Cook Islands', dial: '+682' },
  { iso: 'NU', zh: '纽埃', en: 'Niue', dial: '+683' },
  { iso: 'NF', zh: '诺福克岛', en: 'Norfolk Island', dial: '+672' },
  { iso: 'TK', zh: '托克劳', en: 'Tokelau', dial: '+690' },
  { iso: 'WF', zh: '瓦利斯和富图纳', en: 'Wallis and Futuna', dial: '+681' },
  { iso: 'YT', zh: '马约特', en: 'Mayotte', dial: '+269' },
  { iso: 'SH', zh: '圣赫勒拿', en: 'Saint Helena', dial: '+290' },
  { iso: 'FK', zh: '福克兰群岛', en: 'Falkland Islands', dial: '+500' },
  { iso: 'PM', zh: '圣皮埃尔和密克隆', en: 'Saint Pierre and Miquelon', dial: '+508' }
]

/** 按国家名(中/英)/区号/ISO 搜索；空查询返回全量 */
export function filterCountries(query) {
  const q = String(query ?? '').trim().toLowerCase()
  if (!q) return COUNTRY_CODES
  const qDial = q.startsWith('+') ? q : `+${q}`
  return COUNTRY_CODES.filter(
    (c) =>
      c.en.toLowerCase().includes(q) ||
      c.zh.includes(q) ||
      c.dial.startsWith(qDial) ||
      c.iso.toLowerCase() === q
  )
}

/** ISO2 → 国旗 emoji */
export function flagEmoji(iso) {
  return String.fromCodePoint(...[...iso.toUpperCase()].map((ch) => 0x1f1a5 + ch.charCodeAt(0)))
}

/** ISO2 → 区号；未知返回 null */
export function dialOf(iso) {
  const hit = COUNTRY_CODES.find((c) => c.iso === iso)
  return hit ? hit.dial : null
}
